name: Mongodump & Mongorestore action
description: GitHub action to run mongodump/mongorestore commands

inputs:
  connection-string:
    required: true
    description: 'The connection string to the MongoDB database'
  compress:
    required: false
    default: 'false'
    description: 'Compress the output file'
  additional-args:
    required: false
    description: 'Additional arguments to pass to mongodump/mongorestore command'
  mongo-command:
    required: false
    default: 'mongodump'
    description: 'The mongodump/mongorestore command to run'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mongo-command }}
    - ${{ inputs.connection-string }}
    - ${{ inputs.additional-args }}
    - ${{ inputs.compress }}
  post-entrypoint: '/action/cleanup.sh'

branding:
  icon: 'database'
  color: 'green'
