name: mongodump of a MongoDB database action
description: Generate a mongodump of a MongoDB database

inputs:
  connection-string:
    required: true
    description: 'The connection string to the MongoDB database'
  compress:
    required: false
    default: 'false'
    description: 'Compress the output file'
  additional-args:
    required: false
    description: 'Additional arguments to pass to mongodump command'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.connection-string }}
    - ${{ inputs.additional-args }}
    - ${{ inputs.compress }}
  post-entrypoint: '/action/cleanup.sh'

branding:
  icon: 'database'
  color: 'green'
