name: Tests
run-name: ${{ github.actor }} requested tests of action

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongo-version: [4, 5, 6, 7]
    services:
      database:
        image: mongo:${{ matrix.mongo-version }}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          mongo-command: mongorestore
          connection-string: mongodb://root:root@database:27017
          compress: true
          additional-args: '--tlsInsecure'
      - uses: actions/upload-artifact@v4
        with:
          name: dump-mongo${{ matrix.mongo-version }}
          path: ${{ github.workspace }}/dump
